name: Pull Request

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - run: earthly --ci +lint
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        base-image:
          - quay.io/kairos/core-ubuntu-20-lts:v1.6.0
          - quay.io/kairos/core-ubuntu-22-lts:v1.6.0
        microk8s-version:
          - 1.24
          - 1.25
        platform:
          - linux/amd64
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - run: earthly --ci --platform=${{ matrix.platform }} +docker --MICROK8S_CHANNEL=${{ matrix.microk8s-version }} --BASE_IMAGE=${{ matrix.base-image }}
